### ISSUE TITLE
About the co-peak size

### ISSUE THREAD

**Issue by Spark001** [KuangJuiHsu/DeeoCO3#4]
Hi,

That's a very interesting work and I have a question about this paper and hope you can help me.
    
You resize the images to 448x448 and stimulate the co-peak with fixed 3x3x3x3 size. However the object sizes are various in different images, how does the co-peak loss to handle this varience? 

Thanks.

**Comment by KuangJuiHsu** [comment]
Hi,

The question is very good, but I don't handle it.

The co-peaks can localize the object location, so the different object sizes are considered.

Then, in the second stage, the true object shape can be obtained with MCG proposals.

However, if the multi-scale cues are used, the performance may be improved.

**Comment by Spark001** [comment]
Such a quick reply !

"In the second stage, the true object shape can be obtained with MCG proposals", you have a point there, however I think you should enhance the statements of co-peaks' significance. After all, compared with PRM, I think the co-peak search should be the most valuable spotlight in your paper.

By the way, did you visualize the co-peak regions in images ? And are there any regular patterns about the positions of co-peak regions? Are they usually on discriminative parts? or plain parts?

Thanks.

**Comment by KuangJuiHsu** [comment]
Sorry for my late reply because I prepare for the paper submission.

Thanks for your suggestion. The co-peak search can find the localization of the instance under an unsupervised setting, and this is actually a major contribution.

Sure. I have visualized these peaks. These peaks usually appear in the common and discriminative parts, but the limitation is that an object may contain more than one peak. Therefore, NMS is needed to filter the redundant proposals.
