### ISSUE TITLE
Results of other methods!

### ISSUE THREAD

**Issue by ltp1995** [KuangJuiHsu/DeeoCO3#7]
Hi, could you share the results of all other instance-aware results compared in Table2 of your paper, 
to promote the rapid development of instance co-segmentation, thanks a lot!

**Comment by KuangJuiHsu** [comment]
Hi, @ltp1995

Sorry for my late reply.

You could check the following link: 
https://drive.google.com/open?id=1ZUtmbWj7R5Kw9C8_xczPQCW63zKyGw7m

This file contains the paper results, and it is about 218GB.

However, in fact, I am sorry because I forget what this file contains, and I will check this file as soon as possible.

If you download this file and still have any questions, please use this issue, and I will report the update as soon as possible.
